# env vars
VSCODE_GIT_ASKPASS_MAIN=/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js
<D=
?F=
CWEAVE=cweave
?D=
@D=
@F=
PC=pc
CURDIR=/Users/shaws/code/pylua
SHELL=/bin/sh
RM=rm -f
IN=test/argv.lua
CO=co
PREPROCESS.F=f77    -F
LINK.m=cc    
LINK.o=cc  
OUTPUT_OPTION=-o 
COMPILE.cpp=c++    -c
MAKEFILE_LIST= run.make
VSCODE_INJECTION=1
XDG_DATA_DIRS=/usr/local/share:/usr/share:/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/contrib/terminal/browser/media/fish_xdg_data:/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/contrib/terminal/browser/media/fish_xdg_data:/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/contrib/terminal/browser/media/fish_xdg_data
CC=cc
__CFBundleIdentifier=com.microsoft.VSCode
CHECKOUT,v=+co   
WASMER_DIR=/Users/shaws/.wasmer
LUA=lua
USER=shaws
LEX.m=lex  -t
CPP=cc -E
LINK.cc=c++    
PATH=/opt/homebrew/opt/*/bin:/opt/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/share/dotnet:~/.dotnet/tools:/opt/homebrew/opt/*/bin:/opt/local/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:/opt/homebrew/bin:/Applications/Racket v8.5/bin:/Users/shaws/.wasmer/bin:/Users/shaws/.wasmer/globals/wapm_packages/.bin:/Users/shaws/wasmtime/bin:/Users/shaws/Library/Python/3.9/bin:/Users/shaws/.local/bin:/Users/shaws/code/local/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:/opt/homebrew/bin:/Applications/Racket v8.5/bin:/Users/shaws/.wasmer/bin:/Users/shaws/.wasmer/globals/wapm_packages/.bin:/Users/shaws/wasmtime/bin:/Users/shaws/Library/Python/3.9/bin:/Users/shaws/.local/bin:/Users/shaws/code/local/bin
LD=ld
TEXI2DVI=texi2dvi
YACC=yacc
COMPILE.mod=m2c   
ARFLAGS=rv
LINK.r=f77    
LINT=lint
COMPILE.f=f77   -c
LINT.c=lint   
YACC.m=yacc 
LINK.p=pc    
YACC.y=yacc 
AR=ar
.FEATURES=target-specific order-only second-expansion else-if archives jobserver check-symlink
TANGLE=tangle
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.KCdRDEdeEs/Listeners
GET=get
%F=
DISPLAY=/private/tmp/com.apple.launchd.37wZEKAbuH/org.xquartz:0
COMPILE.F=f77    -c
CTANGLE=ctangle
.LIBPATTERNS=lib%.so lib%.a
LINK.C=c++    
PWD=/Users/shaws/code/pylua
LINK.S=cc    
PREPROCESS.r=f77    -F
ORIGINAL_XDG_CURRENT_DESKTOP=undefined
LINK.s=cc   
HOME=/Users/shaws
MAKEFILEPATH=/Library/Developer/CommandLineTools/Makefiles
-*-command-variables-*-=IN=test/argv.lua
LOGNAME=shaws
^D=
MAKELEVEL=0
COMPILE.m=cc    -c
XPC_FLAGS=0x0
COLORTERM=truecolor
MAKE=/Library/Developer/CommandLineTools/usr/bin/make
SHLVL=7
WASMER_CACHE_DIR=/Users/shaws/.wasmer/cache
AS=as
PREPROCESS.S=cc -E 
MAKEOVERRIDES=IN=test/argv.lua
COMPILE.p=pc    -c
MAKE_VERSION=3.81
EDITOR=/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code
FC=f77
.DEFAULT_GOAL=
TERM_SESSION_ID=2BCDF09B-1C6E-4966-91F3-17B35418905B
%D=
WEAVE=weave
MAKE_COMMAND=/Library/Developer/CommandLineTools/usr/bin/make
LINK.cpp=c++    
F77=f77
COMPILE.cc=c++    -c
VSCODE_GIT_ASKPASS_EXTRA_ARGS=--ms-enable-electron-run-as-node
TERM_PROGRAM=vscode
.VARIABLES=VSCODE_GIT_ASKPASS_MAIN <D ?F CWEAVE ?D @D @F PC CURDIR SHELL RM IN CO PREPROCESS.F LINK.m LINK.o OUTPUT_OPTION COMPILE.cpp MAKEFILE_LIST VSCODE_INJECTION XDG_DATA_DIRS CC __CFBundleIdentifier CHECKOUT,v WASMER_DIR LUA USER LEX.m CPP LINK.cc PATH LD TEXI2DVI YACC COMPILE.mod ARFLAGS LINK.r LINT COMPILE.f LINT.c YACC.m LINK.p YACC.y AR .FEATURES TANGLE SSH_AUTH_SOCK GET %F DISPLAY COMPILE.F CTANGLE .LIBPATTERNS LINK.C PWD LINK.S PREPROCESS.r ORIGINAL_XDG_CURRENT_DESKTOP LINK.s HOME MAKEFILEPATH -*-command-variables-*- LOGNAME ^D MAKELEVEL COMPILE.m XPC_FLAGS COLORTERM MAKE SHLVL MAKE_VARS WASMER_CACHE_DIR AS PREPROCESS.S MAKEOVERRIDES COMPILE.p MAKE_VERSION EDITOR FC .DEFAULT_GOAL TERM_SESSION_ID %D WEAVE MAKE_COMMAND LINK.cpp F77 COMPILE.cc VSCODE_GIT_ASKPASS_EXTRA_ARGS TERM_PROGRAM .VARIABLES TMPDIR *F VSCODE_GIT_ASKPASS_NODE MallocNanoZone LEX MAKEFLAGS MFLAGS *D TERM_PROGRAM_VERSION LEX.l XPC_SERVICE_NAME +D COMPILE.r +F M2C __CF_USER_TEXT_ENCODING COMMAND_MODE GIT_ASKPASS MAKEFILES <F CXX COFLAGS COMPILE.def COMPILE.C TEST_GIT_TOKEN ^F COMPILE.S LINK.F SUFFIXES COMPILE.c LINK.c COMPILE.s .INCLUDE_DIRS VSCODE_GIT_IPC_HANDLE MAKEINFO TEX LANG TERM F77FLAGS LINK.f GNUMAKE
TMPDIR=/var/folders/7p/cq7v4f3x1t54wbp55601nsrc0000gn/T/
*F=
VSCODE_GIT_ASKPASS_NODE=/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)
MallocNanoZone=0
LEX=lex
MAKEFLAGS=
MFLAGS=
*D=
TERM_PROGRAM_VERSION=1.80.1
LEX.l=lex  -t
XPC_SERVICE_NAME=application.com.microsoft.VSCode.45087820.45087827.860A9785-32B8-4D39-92A7-DCE4738241D2
+D=
COMPILE.r=f77    -c
+F=
M2C=m2c
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
COMMAND_MODE=unix2003
GIT_ASKPASS=/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh
MAKEFILES=
<F=
CXX=c++
COFLAGS=
COMPILE.def=m2c   
COMPILE.C=c++    -c
TEST_GIT_TOKEN=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
^F=
COMPILE.S=cc    -c
LINK.F=f77    
SUFFIXES=.out .a .ln .o .c .cc .C .cpp .p .f .F .m .r .y .l .ym .lm .s .S .mod .sym .def .h .info .dvi .tex .texinfo .texi .txinfo .w .ch .web .sh .elc .el
COMPILE.c=cc    -c
LINK.c=cc    
COMPILE.s=as  
.INCLUDE_DIRS=/usr/local/include
VSCODE_GIT_IPC_HANDLE=/var/folders/7p/cq7v4f3x1t54wbp55601nsrc0000gn/T/vscode-git-d2a3c46c3f.sock
MAKEINFO=makeinfo
TEX=tex
LANG=en_US.UTF-8
TERM=xterm-256color
F77FLAGS=
LINK.f=f77   
GNUMAKE=YES
